# This is for deploying release tags

name: GitHub Actions Vercel Preview Deployment
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on:
  release:
    types: [published]
jobs:
  Deploy-Preview:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Node.js v18
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
          rubygems: latest
          bundler-cache: true

      - uses: pnpm/action-setup@v2
        with:
          version: 7

      - name: use node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'pnpm'
          cache-dependency-path: |
            pnpm-lock.yaml

      - name: Install dependencies
        run: pnpm install
      - name: Install Vercel CLI
        run: npm install --global vercel@canary
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build Project Artifacts
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy Project Artifacts to Vercel
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          VERCEL_DEPLOYMENT_URL=$(vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }})
          KEBAB_VERSION=$(echo "$GITHUB_REF_NAME" | sed 's/\./-/g')
          RELEASE_DOMAIN="rhino-editor-release-$KEBAB_VERSION.vercel.app"
          RELEASE_URL="https://$RELEASE_DOMAIN"
          vercel alias "$VERCEL_DEPLOYMENT_URL" "$RELEASE_DOMAIN" --token=${{ secrets.VERCEL_TOKEN }}
          ./scripts/modify-release-notes
