name: Tests
on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "*"

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  rails-test:
    runs-on: ubuntu-latest
    env:
      CI: true
      RAILS_ENV: test
      AWS_S3_BUCKET: my-bucket
      AWS_S3_ACCESS_KEY: minioadmin
      AWS_S3_SECRET_KEY: minioadmin
      AWS_S3_ENDPOINT: http://127.0.0.1:9000
    strategy:
      matrix:
        ruby: ['2.7', '3.0', '3.1']
        node-version: [16.x, 18.x]
    services:
        s3:
          # See: https://stackoverflow.com/a/64188150/5155484
          # https://github.com/minio/minio/discussions/16099
          image: minio/minio:edge-cicd
          options: --health-cmd "curl -s http://localhost:9000/minio/health/live"
          env:
            MINIO_ROOT_USER: minioadmin
            MINIO_ROOT_PASSWORD: minioadmin
    steps:
    - uses: actions/checkout@v3
    - uses: microsoft/playwright-github-action@v1

    - name: Install libvips
      run: sudo apt -y install libvips

    - name: Set parallel workers env variable
      run: echo "PARALLEL_WORKERS=$(expr $(nproc) \* 6)" >> $GITHUB_ENV

    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true

    - uses: pnpm/action-setup@v2
      with:
        version: 7.x.x
        run_install: false

    - name: use node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'pnpm'
        cache-dependency-path: |
          pnpm-lock.yaml
          tests/rails/pnpm-lock.yaml

    - name: Fetch mc client
      run: curl -o ./mc -# https://dl.min.io/client/mc/release/linux-amd64/mc && chmod +x ./mc
    - name: Create the dev bucket
      run: ./mc mb my-bucket
    - name: Remove mc client
      run: rm -v ./mc

    - name: Install via pnpm
      run: |
        pnpm run setup
    - name: Tests
      run: |
        pnpm run build
        pnpm run test:ci
