name: Actions
on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "*"
jobs:
  # We don't currently have any tests that onyl run with JS. perhaps in the future.
  # js-test:
  #   runs-on: ubuntu-latest
  #   strategy:
  #     matrix:
  #       node-version: [16.x, 18.x]

    # steps:
    #   - uses: actions/checkout@v3

    #   # For playwright
    #   - uses: microsoft/playwright-github-action@v1

    #   - uses: pnpm/action-setup@646cdf48217256a3d0b80361c5a50727664284f2
    #     with:
    #       version: 6.22.1
    #   - name: use node.js ${{ matrix.node-version }}
    #     uses: actions/setup-node@v3
    #     with:
    #       node-version: ${{ matrix.node-version }}
    #       cache: 'pnpm'
    #       cache-dependency-path: |
    #         pnpm-lock.yaml
    #   - name: Install via pnpm
    #     run: |
    #       pnpm install
    #   - name: lint, and test
    #     run: |
    #       pnpm lint
    #       pnpm test:ci
  rails-test:
    runs-on: ubuntu-latest
    env:
      CI: true
      RAILS_ENV: test
    strategy:
      matrix:
        ruby: ['2.7', '3.0', '3.1']
        node-version: [16.x, 18.x]
    steps:

    - uses: actions/checkout@v3
    - uses: microsoft/playwright-github-action@v1
    - name: Setup docker
      run: cd tests/rails && docker compose up --build -d --health-cmd "curl --fail http://0.0.0.0:9000/minio/health/live || exit 1" --health-interval=1s --timeout=10s

    - name: Install libvips
      run: sudo apt -y install libvips

    - name: Set parallel workers env variable
      run: echo "PARALLEL_WORKERS=$(expr $(nproc) \* 6)" >> $GITHUB_ENV

    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - uses: pnpm/action-setup@646cdf48217256a3d0b80361c5a50727664284f2
      with:
        version: 6.22.1
    - name: use node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'pnpm'
        cache-dependency-path: |
          pnpm-lock.yaml
          tests/rails/pnpm-lock.yaml

    - name: Install via pnpm
      run: |
        pnpm install
        cd tests/rails
        pnpm install
        bundle install
        cd -
    - name: Tests
      run: |
        pnpm run build
        pnpm run test:ci
