name: Tests
on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "*"

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  rails-test:
    runs-on: ubuntu-latest
    env:
      CI: true
      RAILS_ENV: test
      AWS_ACCESS_KEY_ID: minioadmin
      AWS_SECRET_ACCESS_KEY: minioadmin
      AWS_DEFAULT_REGION: us-east-1
      AWS_BUCKET: my-bucket
      AWS_URL: "http://127.0.0.1:9000"
      AWS_ENDPOINT: "http://127.0.0.1:9000"
      AWS_USE_PATH_STYLE_ENDPOINT: true
    strategy:
      matrix:
        ruby: ['2.7', '3.0', '3.1']
        node-version: [16.x, 18.x]
    steps:
    - uses: actions/checkout@v3
    - uses: microsoft/playwright-github-action@v1

    - name: Download MinIO S3 server and client
      run: |
        wget https://dl.minio.io/server/minio/release/linux-amd64/minio -q -P /usr/local/bin/
        wget https://dl.minio.io/client/mc/release/linux-amd64/mc -q -P /usr/local/bin/
        chmod +x /usr/local/bin/minio
        chmod +x /usr/local/bin/mc
        minio --version
        mc --version

    # - name: Run MinIO S3 server
    #   run: |
    #     mkdir ~/s3
    #     sudo minio server ~/s3 --json > minio-log.json &
    #
    - name: Configure MinIO S3
      run: |
        mkdir -p ~/s3
        sudo mc config host add local http://127.0.0.1:9000 minioadmin minioadmin
        mc mb local/my-bucket --region=us-east-1

    # - name: Upload Minio Logs (optional)
    #   if: failure()
    #   uses: actions/upload-artifact@v2
    #   with:
    #     name: minio
    #     path: minio-log.json

    - name: Install libvips
      run: sudo apt -y install libvips

    # - name: Set parallel workers env variable
    #   run: echo "PARALLEL_WORKERS=$(expr $(nproc) \* 6)" >> $GITHUB_ENV

    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true

    - uses: pnpm/action-setup@v2
      with:
        version: 7.x.x
        run_install: false

    - name: use node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'pnpm'
        cache-dependency-path: |
          pnpm-lock.yaml
          tests/rails/pnpm-lock.yaml

    - name: Install via pnpm
      run: |
        pnpm run setup
    - name: Build
      run: |
        pnpm run build
    - name: Test
      run: |
        # curl -m 10 --retry 10 -I 127.0.0.1:9000/minio/health/live
        pnpm run test:ci
